### PR TITLE
Adds logger.

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Adds a logger to match stan-dev/stan#512.

#### Intended Effect:

Updates pystan.

#### How to Verify:

Run tests.

#### Side Effects:

None. All behavior should be the same.

#### Documentation:

None.

#### Reviewer Suggestions: 

@ariddell 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Stan Group

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ariddell** [comment]
Looks good! Thanks for doing this.

Are we going to have to adjust this again to make a release by changing the library locations back to ``stan_math_2.16``? If so, I wonder if we could just hold off on merging this.

**Comment by syclik** [comment]
I believe the plan is to no longer shift the library locations. @seantalts can verify.

**Comment by seantalts** [comment]
Yep, that's right - no more renaming directories for releases.

**Comment by ariddell** [comment]
This is failing on a boost include. I think some more adjustments of library paths need to be made.

I'll update develop to use the new submodule. Once rebased, this should work fine.

**Comment by syclik** [comment]
Thanks. Sorry about that.

**Comment by ariddell** [comment]
Seems like this is the error holding us back:

```
/home/travis/miniconda3/envs/env_name/lib/python3.3/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.2.9/Eigen/src/Cholesky/LLT.h: In instantiation of ‘class Eigen::LLT<Eigen::Ref<Eigen::Matrix<double, -1, -1> >, 1>’:

/home/travis/miniconda3/envs/env_name/lib/python3.3/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat/fun/cholesky_decompose.hpp:247:73:   required from here

/home/travis/miniconda3/envs/env_name/lib/python3.3/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.2.9/Eigen/src/Cholesky/LLT.h:54:10: error: ‘Options’ is not a member of ‘Eigen::LLT<Eigen::Ref<Eigen::Matrix<double, -1, -1> >, 1>::MatrixType {aka Eigen::Ref<Eigen::Matrix<double, -1, -1> >}’

     enum {
```

@syclik Does this look familiar? I can ``git bisect`` to figure out when it was introduced if not.

**Comment by syclik** [comment]
I've never seen that before. It all worked locally. Should I retry?

**Comment by ariddell** [comment]
I'll track it down. The error is new and coming from the CI. Whatever caused it was introduced after stan-dev/stan@40fb0dd56f728f707fbb216eb54d59cf9e0880f7 (Apr 24)

**Comment by syclik** [comment]
Thanks. If there's anything specific, please tag me and I'll hunt it down.
Sorry this is taking a little more effort than I had imagined.

**Comment by ariddell** [comment]
Fixed it, I think. New PR is #349.
